### ISSUE TITLE
(Go) How to create instance resource when there are multiple networks available?

### ISSUE THREAD

**Issue by yankcrime** [pulumi/pulumi-openstack#14]
👋 

I'm struggling to work out exactly what I should pass to `compute.NewInstance.Networks` in order to be able to launch an instance when there is more than one network available.   The comment in the `compute` package states an array of "one or more networks", but the 'object' structure it mentions isn't shown anywhere - I assume this is lifted from the Terraform docs.  I've tried a few things such as passing in a list containing the UUID of the network I want to use as well as other data structures such as struct which mirrors how it's done in Gophercloud but no dice.

Can you shed some light on what this should look like?

**Comment by Frassle** [comment]
The go code generator doesn't really handle substructure at the moment. Pretty easy to take a look at the terraform documenation or the typescript pulumi code to see what the structures are for now. "Networks" is an array of structs that look like this:

    { accessNetwork: boolean, fixedIpV4: string, fixedIpV6: string, mac: string, name: string, port: string, uuid: string }

I think it's sufficient to just pass the name (that's the network name) and leave everything thing else nil.

**Comment by lukehoban** [comment]
That's right.  The typings are dropped from the Go projection currently (see https://github.com/pulumi/pulumi-aws/issues/248), but in TypeScript for example, you can see the type of this structure here (which is what @Frassle ) includes above as well. 

https://github.com/pulumi/pulumi-openstack/blob/master/sdk/nodejs/compute/instance.ts#L109

Giving this structure a separate name and documentation per property is part of https://github.com/pulumi/pulumi-terraform/issues/163.

Closing out since the issues to improve this for Go in particular are tracked elsewhere - but feel free to open another issue if there is anything else we should be tracking here.
